import Carousel1 from "./svgs/Carousel_1.svg";
import Carousel2 from "./svgs/Carousel2.svg";
import Carousel3 from "./svgs/Carousel3.svg";
import Carousel4 from "./svgs/Carousel4.svg";
import Carousel5 from "./svgs/Carousel5.svg";
import "./svgs/Ellipse-1.svg";
import "./svgs/Ellipse-2.svg";
import "./svgs/Ellipse-3.svg";
import "./svgs/Ellipse-4.svg";
import "./svgs/Ellipse-5.svg";
import "./svgs/Frame.svg";
import "./svgs/GreaterThan.svg";
import "./svgs/Vector (10).svg";
import "./svgs/Vector (9).svg";
import "./svgs/bx_bxs-book-reader.svg";
import "./svgs/carbon_book.svg";
import cart from "./svgs/cart.svg";
import email from "./svgs/email.svg";
import facebook from "./svgs/facebook.svg";
import "./svgs/footer_1.svg";
import "./svgs/footer_2.svg";
import "./svgs/footer_3.svg";
import "./svgs/icn arrow-right .icn-xs.svg";
import "./svgs/icon akar-icons-calendar.svg";
import "./svgs/icon ant-design-area-chart-outlined.svg";
import "./svgs/icon carbon-chart-area-smooth.svg";
import instagram from "./svgs/instagram.svg";
import likes from "./svgs/likes.svg";
import login from "./svgs/login.svg";
import "./svgs/logo.svg";
import p1 from "./svgs/p1.svg";
import "./svgs/p2.svg";
import "./svgs/p3.svg";
import p3 from "./svgs/p31.svg";
import phone from "./svgs/phone.svg";
import "./svgs/product-1.svg";
import "./svgs/product-2.svg";
import "./svgs/product-3.svg";
import "./svgs/product-4.svg";
import "./svgs/product-5.svg";
import "./svgs/product-6.svg";
import "./svgs/product-7.svg";
import "./svgs/product-8.svg";
import "./svgs/product-9.svg";
import search from "./svgs/search.svg";
import technology from "./svgs/technology 1.svg";
import togglebtn from "./svgs/togglebtn.svg";
import twitter from "./svgs/twitter.svg";
import "./svgs/uil_arrow-growth.svg";
import "./svgs/unsplash_75EFpyXu3Wg.svg";
import p2 from "./svgs/unsplash_Bd7gNnWJBkU (1).svg";
import "./svgs/unsplash_Lks7vei-eAg (1).svg";
import "./svgs/unsplash_Lks7vei-eAg.svg";
import "./svgs/unsplash_ruJm3dBXCqw.svg";
import client1 from "./svgs/vector-1.svg";
import client2 from "./svgs/vector-2.svg";
import client3 from "./svgs/vector-3.svg";
import client4 from "./svgs/vector-4.svg";
import client5 from "./svgs/vector-5.svg";
import client6 from "./svgs/vector-6.svg";
import youtube from "./svgs/youtube.svg";

export const Carousel_1 = Carousel1;
export const Carousel_2 = Carousel2;
export const Carousel_3 = Carousel3;
export const Carousel_4 = Carousel4;
export const Carousel_5 = Carousel5;
// Dark-Navbar
export const phone_img = phone;
export const email_img = email;
export const instagram_img = instagram;
export const facebook_img = facebook;
export const twitter_img = twitter;
export const youtube_img = youtube;
//Light-Navbar
export const login_img = login;
export const search_img = search;
export const cart_img = cart;
export const likes_img = likes;
export const toggle_btn_img = togglebtn;
// Shop-Header
export const technology_img = technology;
//Clients
export const client_img_1 = client1;
export const client_img_2 = client2;
export const client_img_3 = client3;
export const client_img_4 = client4;
export const client_img_5 = client5;
export const client_img_6 = client6;
//Shopping-Card
export const shopping_card_1 = p1;
export const shopping_card_2 = p2;
export const shopping_card_3 = p3;
